version: "3"

services:
  pihole:
    container_name: pihole
    image: scantineau/pihole:latest
    network_mode: host
    environment:
      TZ: 'Europe/Brussels'
      WEBPASSWORD: 'a strong password'
      ServerIP : 'your lan ip'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

