#!/usr/bin/env bash
set -eu
source hooks/.config

IMAGE_NAME="${IMAGE_NAME//index.docker.io\/}"
for ARCH in ${ARCHITECTURES_TO_BUILD[@]}; do
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  echo "Pushing ${IMAGE_NAME}-${ARCH}"
  docker push ${IMAGE_NAME}-${ARCH}
done

echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
echo "Creating manifest ${IMAGE_NAME}"
manifests=""
for ARCH in ${ARCHITECTURES_TO_BUILD[@]}; do
  manifests="${manifests} ${IMAGE_NAME}-${ARCH}"
done
docker manifest create ${IMAGE_NAME} $manifests

for ARCH in ${ARCHITECTURES_TO_BUILD[@]}; do
  VARIANT=
  if [ "${manifest_variant_map[${ARCH}]}" != "" ]; then
    VARIANT="--variant ${manifest_variant_map[${ARCH}]}"
  fi

  echo "Annotating manifest for ${IMAGE_NAME}-${ARCH}"
  docker manifest annotate ${IMAGE_NAME} \
    ${IMAGE_NAME}-${ARCH} \
    --os linux \
    --arch ${manifest_architecture_map[${ARCH}]} \
    $VARIANT
done

echo "Pushing manifest ${IMAGE_NAME}"
docker manifest push --purge "${IMAGE_NAME}"
